# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: x_client/grpc/x_client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cx_client/grpc/x_client.proto\x12\x08x_client\"5\n\x07NdArray\x12\r\n\x05\x64type\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\",\n\x07Request\x12!\n\x06images\x18\x01 \x03(\x0b\x32\x11.x_client.NdArray\"K\n\x08Response\x12\x1e\n\x03\x62ox\x18\x01 \x03(\x0b\x32\x11.x_client.NdArray\x12\x1f\n\x04pose\x18\x02 \x03(\x0b\x32\x11.x_client.NdArray2=\n\x07XClient\x12\x32\n\x05infer\x12\x11.x_client.Request\x1a\x12.x_client.Response\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'x_client.grpc.x_client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NDARRAY._serialized_start=42
  _NDARRAY._serialized_end=95
  _REQUEST._serialized_start=97
  _REQUEST._serialized_end=141
  _RESPONSE._serialized_start=143
  _RESPONSE._serialized_end=218
  _XCLIENT._serialized_start=220
  _XCLIENT._serialized_end=281
# @@protoc_insertion_point(module_scope)
