# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from x_client.grpc import x_client_pb2 as x__client_dot_grpc_dot_x__client__pb2


class XInferenceServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer = channel.stream_unary(
                '/x_client.XInferenceServer/infer',
                request_serializer=x__client_dot_grpc_dot_x__client__pb2.Request.SerializeToString,
                response_deserializer=x__client_dot_grpc_dot_x__client__pb2.Response.FromString,
                )


class XInferenceServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def infer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XInferenceServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer': grpc.stream_unary_rpc_method_handler(
                    servicer.infer,
                    request_deserializer=x__client_dot_grpc_dot_x__client__pb2.Request.FromString,
                    response_serializer=x__client_dot_grpc_dot_x__client__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'x_client.XInferenceServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class XInferenceServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def infer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/x_client.XInferenceServer/infer',
            x__client_dot_grpc_dot_x__client__pb2.Request.SerializeToString,
            x__client_dot_grpc_dot_x__client__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
